- hosts: "{{ hosts }}"
  gather_facts: no
  serial: 1
  tasks:
    - name:  Get the DockerAppId which is running. step:1/3
      shell: docker ps|egrep '{{ DockerApp }}[\ |:]'|awk '{print $1}'
      register: DockerAppId
    - name: Docker app stop. step:2/3
      command: docker stop "{{ DockerAppId.stdout }}"
      register: msg2
      failed_when: "'FAILED' in msg2.stderr"
    - name: Docker app start. step:3/3
      command: docker start "{{ DockerAppId.stdout }}"


    - name: LoopEurekaHealthCheck until successful, max time(2min) . step:healthcheck
      script: eureka_health_check2.sh "{{ AppSpringName }}"
      tags: eureka


