- hosts: "{{ hosts }}"
  gather_facts: no
  serial: 1
  tasks:
    - name:  sync to the destination
      synchronize:
        src: "{{ deploy_src_path }}"
        dest: "{{ deploy_dest_path }}"
        delete: "{{ delete_enable }}"
      tags: common

    - name:  sync php_frontend to the destination
      synchronize:
        src: "{{ deploy_src_path }}"
        dest: "{{ deploy_dest_path }}"
        delete: "{{ delete_enable }}"
        rsync_opts:
          - "--no-motd"
          - "--exclude=RedisConnect.php"
          - "--exclude=config"
          - "--exclude=runtime"
      tags: php_frontend

    - name: change dir owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        recurse: yes
      tags: dir_change_owner

    - name: change file owner
      file:
        path: "{{ deploy_dest_path }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      tags: fir_change_owner
