- hosts: "{{ hosts }}"
  gather_facts: no
  serial: 1
  tasks:
    - name: Step:1/5:Get the AppInstance ID(e.host:port) from eureka. 
      shell: curl -s "{{ EurekaUrl }}" |grep `hostname`:"{{ AppSpringName }}:" |awk -F / '{print $3}'
      register: AppInstance
    - name: Step:2/5:Get the DockerAppId which is running. 
      shell: docker ps|egrep '{{ DockerApp }}(\ |:|-20)'|awk '{print $1}'
      register: DockerAppId
    - name: Step:3/5:Deregister service.
      shell: curl  -s --max-time 3 http://"{{ AppInstance.stdout }}"/health/deregister
    - name: Step:4/5:Securyty wait times for eureka server&client cache refresh (default 60s).
      command: sleep "{{ WaitTimes }}"
    - name: Step:5/5:Docker stop app. 
      command: docker stop "{{ DockerAppId.stdout }}"
      register: msg2
      failed_when: "'FAILED' in msg2.stderr"  
  



